[package]
name = "worker"
version = "0.0.1"
authors = ["Theron Boerner <hunterboerner@gmail.com>"]

[dependencies]
docopt = "*"
docopt_macros = "*"
hyper = "*"
tempdir = "*"
rustc-serialize = "*"
regex = "*"
regex_macros = "*"
